"""add fingerprint to subscription's model. specify email binary length in user model

Revision ID: 0fa1c491634b
Revises: 
Create Date: 2026-03-06 02:59:28.756406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa1c491634b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fingerprint', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_subscriptions_fingerprint'), ['fingerprint'], unique=True)

    op.execute("""
    UPDATE subscriptions
    SET fingerprint = CONCAT('temp_value', id)
    WHERE fingerprint is NULL
    """)

    with op.batch_alter_table("subscriptions") as batch_op:
        batch_op.alter_column(
            "fingerprint",
            existing_type=sa.String(length=64),
            nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_fingerprint'))
        batch_op.drop_column('fingerprint')

    # ### end Alembic commands ###
