from dotenv import load_dotenv
import requests
import time
import datetime
import os
import base64

load_dotenv()

class Mpesa:

    def __init__(
            self,
            mpesa_contact,
            transaction_type,
            business_short_code,
            amount,
            account_ref,
            transaction_desc
    ):
        self.consumer_key = os.getenv("CONSUMER_KEY")
        self.consumer_secret = os.getenv("CONSUMER_SECRET")
        self.access_token = ""
        self.expires_at = 0
        self.mpesa_contact = mpesa_contact
        self.transaction_type = transaction_type   # if paybill:
                                                       # transaction_type == "CustomerPayBillOnline"
                                                    # else:
                                                        # other option given by daraja - matching "till number"
        self.business_short_code = business_short_code  # check if C2B works
        self.amount = amount
        self.account_ref = account_ref
        self.transaction_desc = transaction_desc

    def get_access_token(self):
        """sends a get request to Daraja
        updates the access token's expiry time
        returns the access token"""


        try:
            response = requests.get(
                url="https://sandbox.safaricom.co.ke/oauth/v1/generate",
                headers={
                "Authorization": "Basic eVNPeFFuZDBBakZQWFFtajFxcHVXT043dVdxNkE1ZUpBb05LYkdqU0RmdE1XUDVxOk5EYnZXNDNSdEVqdVlMZVFnY2R2QUVoa2F5eDFPSEE3eHlvRUNBVkpEV1lobzFUWkpidEsyZ0U5dHQ0UEc1SEg"
            },
                params={
                "grant_type":"client_credentials"
            }
            )

            if response.status_code == 200:
                self.access_token = response.json()["access_token"]
                self.expires_at = (time.time() + int(response.json()["expires_in"]) - 45)
                return self.access_token
            else:
                return response.json()["errorMessage"]

        except KeyError:
            return "No json was returned"

    def token_cache(self):
        """returns the same access token within a 3600-second window.
        requests for a new access token if time elapsed - when the token expires"""

        if time.time() < self.expires_at:
            return self.access_token
        else:
            return self.get_access_token()

    def stk_push(self):
        """
            triggers an STK Push to mpesa,
            returns status message
            redirects callback url to designed route
        """

        timestamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
        encode_bytes = base64.b64encode(
            f'{self.business_short_code}{os.getenv("EXPRESS_PASSKEY")}{timestamp}'.encode("utf-8")
        )
        password = encode_bytes.decode("utf-8")

        response = requests.post(
            url="https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest",
            headers={
                "Authorization":f"Bearer {self.access_token}",
                "Content-Type":"application/json"
            },
            json= {
                "BusinessShortCode":self.business_short_code,
                "Password":password,
                "Timestamp": timestamp,
                "TransactionType":self.transaction_type,
                "Amount":self.amount,
                "PartyA":self.mpesa_contact,
                "PartyB":self.business_short_code,
                "PhoneNumber":self.mpesa_contact,
                "CallBackURL":"https://577ea44e0a91.ngrok-free.app/transactions/stk-callback",
                "AccountReference":self.account_ref, # add mechanism to add account number if transaction
                                                                                 # != CustomerPayBillOnline
                "TransactionDesc":self.transaction_desc
            }

        ) # handle error generated by response

        print(response.text)
        response.raise_for_status()

        return response.json()["CustomerMessage"] # message to display when payment is pending
    # use this message to make changes to the transaction - pending
    # store the status and inform the user
    # all in the payments.make_payment route - or a different route
